/******************************************************************************/
/***          Generated by IBExpert 2012.02.21 23/11/2015 19:54:59          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES UTF8;

SET CLIENTLIB 'C:\Program Files\Firebird\Firebird_2_5\WOW64\fbclient.dll';

CREATE DATABASE 'D:\CONTAS_PAGAR.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 4096
DEFAULT CHARACTER SET UTF8 COLLATION UTF8;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE BANCO (
    BAN_CODIGO     INTEGER NOT NULL,
    BAN_DESCRICAO  VARCHAR(100)
);

CREATE TABLE CONDICAOPAGAMENTO (
    CDP_CODIGO           INTEGER NOT NULL,
    CDP_DESCRICAO        VARCHAR(100),
    CDP_PARCELAS         INTEGER,
    CDP_DIAS_VENCIMENTO  INTEGER
);


CREATE TABLE TIPOPAGAMENTO (
    TPG_CODIGO     INTEGER NOT NULL,
    TPG_DESCRICAO  VARCHAR(100)
);

CREATE TABLE TITULOSP (
    TTP_CODIGO           INTEGER NOT NULL,
    TTP_EMP_CODIGO       INTEGER NOT NULL,
    TTP_PES_CODIGO       INTEGER,
    TTP_CTB_CODIGO       INTEGER,
    TTP_CON_CODIGO       INTEGER,
    TTP_DESCRICAO        VARCHAR(100),
    TTP_DT_EMISSAO       DATE,
    TTP_DT_VENCIMENTO    DATE,
    TTP_DT_PAGAMENTO     DATE,
    TTP_DT_BAIXA         DATE,
    TTP_DT_CANCELAMENTO  DATE,
    TTP_TP_TITULO        VARCHAR(30),
    TTP_DESCONTO         NUMERIC(18,2),
    TTP_PARCELA          NUMERIC(10,2),
    TTP_VL_ORIGINAL      NUMERIC(18,2),
    TTP_VL_PAGO          NUMERIC(18,2),
    TTP_VL_TOTAL         NUMERIC(18,2),
    TTP_MR_DIARIA        NUMERIC(18,2),
    TTP_MT_ATRASO        NUMERIC(18,2),
    TTP_SITUACAO         VARCHAR(1),
    TTP_TP_MORA          VARCHAR(1),
    TTP_TP_MULTA         VARCHAR(1)
);



/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE BANCO ADD CONSTRAINT PK_BANCO PRIMARY KEY (BAN_CODIGO);
ALTER TABLE CONDICAOPAGAMENTO ADD CONSTRAINT PK_CONDICAOPAGAMENTO PRIMARY KEY (CDP_CODIGO);
ALTER TABLE TIPOPAGAMENTO ADD CONSTRAINT PK_TIPOPAGAMENTO PRIMARY KEY (TPG_CODIGO);
ALTER TABLE TITULOSP ADD CONSTRAINT PK_TITULOSP PRIMARY KEY (TTP_CODIGO, TTP_EMP_CODIGO);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE TITULOSP ADD CONSTRAINT REL_TTP_CONDICAO FOREIGN KEY (TTP_CON_CODIGO) REFERENCES CONDICAOPAGAMENTO (CDP_CODIGO);
ALTER TABLE TITULOSP ADD CONSTRAINT REL_TTP_CONTAB FOREIGN KEY (TTP_CTB_CODIGO) REFERENCES CONTABANCARIA (CTB_CODIGO);
ALTER TABLE TITULOSP ADD CONSTRAINT REL_TTP_EMPRESA FOREIGN KEY (TTP_EMP_CODIGO) REFERENCES EMPRESA (EMP_COD);
ALTER TABLE TITULOSP ADD CONSTRAINT REL_TTP_PESSOA FOREIGN KEY (TTP_PES_CODIGO) REFERENCES PESSOAS (PESS_CODIGO);



**********************************************************************************
CREATE or ALTER PROCEDURE   atualizatotal
AS
declare variable vencimento DATE;
declare variable vl_original numeric (18,2);
declare variable vl_pago NUMERIC (18,2);
declare variable desconto NUMERIC(18,2);
declare variable mora NUMERIC(18,2);
declare variable atraso NUMERIC(18,2);
declare variable status VARCHAR(1);
declare variable tp_mora VARCHAR(1);
declare variable tp_atraso VARCHAR(1);
declare variable tempresa INTEGER;
begin
for select a.ttp_dt_vencimento,
           a.ttp_vl_original,
           a.ttp_vl_pago,
           a.ttp_desconto,
           a.ttp_mr_diaria,
           a.ttp_mt_atraso,
           a.ttp_situacao,
           a.ttp_tp_mora,
           a.ttp_tp_multa,
           emp_cod
from titulosp a
inner join empresa on emp_cod=ttp_emp_codigo
where ttp_emp_codigo=emp_cod
into :vencimento, :vl_original, :vl_pago, :desconto, :mora,:atraso, :status, :tp_mora, :tp_atraso, :tempresa
do
 begin

    if (:vencimento > current_date ) then
     update titulosp
     set ttp_vl_total=:vl_original WHERE :status='A';

    if (:vencimento < current_date and tp_mora='R' and tp_atraso='R') then
     update titulosp
     set ttp_vl_total=:vl_original+:atraso+(:mora*(current_date-:vencimento)) WHERE :status='A';

    if (:vencimento < current_date and tp_mora='P' and tp_atraso='R') then
     update titulosp
     set ttp_vl_total=:vl_original+:atraso+((:mora*(current_date-:vencimento)/100)*:vl_original)
     WHERE :status='A';

    if (:vencimento < current_date and tp_mora='P' and tp_atraso='P') then
        update titulosp
     set ttp_vl_total=:vl_original+(((:atraso/100)*:vl_original)+((:mora*(current_date-:vencimento)/100)*:vl_original))
     WHERE :status='A';

    if (:vencimento < current_date and tp_mora='R' and tp_atraso='P') then
        update titulosp
     set ttp_vl_total=:vl_original+(((:atraso/100)*:vl_original)+(:mora*(current_date-:vencimento)))
     WHERE :status='A';

    if (:desconto>0 and :vencimento<current_date ) then
        update titulosp
     set ttp_vl_total=:vl_original-:desconto
     WHERE :status='A';

    if (:vl_pago < :vl_original ) then
     update titulosp
     set ttp_vl_total=:vl_original-:vl_pago
     WHERE :status='P';

    suspend;

 end 
end

*********************************************************************************************************************
create trigger atualizar for titulosp
active before insert or update position 0
as
begin
execute procedure atualizatotal;
end

******************************************

seqtitulosp

seqcondicao
