
CREATE GENERATOR GEN_VENDA;
SET GENERATOR GEN_VENDA TO 1;

CREATE GENERATOR GEN_SEQUENCIA;
SET GENERATOR GEN_SEQUENCIA TO 1;


CREATE TABLE EMISSAO_NFE (
    EMI_NUMERO            INTEGER NOT NULL,
    EMI_NOTAFISCAL        NUMERIC(9,0),
    EMI_EMPRESA           INTEGER NOT NULL,
    EMI_SERIE             NUMERIC(9,0),
    EMI_TIPOMOVIMENTACAO  INTEGER NOT NULL,
    EMI_DESCRICAO         VARCHAR(60) NOT NULL,
    EMI_PESSOA            VARCHAR(60) NOT NULL,
    EMI_DTEMISSAO         DATE,
    EMI_DTSAIDA           DATE
);

CREATE TABLE FATURAMENTO (
    FAT_CODIGO_PEDIDO  INTEGER NOT NULL,
    FAT_DESCRICAO      VARCHAR(60),
    FAT_EMPRESA        INTEGER NOT NULL,
    FAT_PESSOA         INTEGER NOT NULL,
    FAT_NOTA           INTEGER,
    FAT_NOTASERIE      INTEGER,
    FAT_DTEMISSAO      DATE,
    FAT_DTSAIDA        DATE,
    FAT_SITAUCAO       VARCHAR(5) DEFAULT 'A',
    FAT_CHAVE_ACESSO   NUMERIC(9,0)
);

CREATE TABLE PEDIDOVENDA (
    PED_NUMERO            INTEGER NOT NULL,
    PED_PESSOA            VARCHAR(60) NOT NULL,
    PED_SEQUENCIA         INTEGER,
    PED_SITUACAO          VARCHAR(5) DEFAULT 'A',
    PED_EMPRESA           INTEGER NOT NULL,
    PED_DEPOSITO          INTEGER NOT NULL,
    PED_PRODUTO           INTEGER NOT NULL,
    PED_DESCRICAO         VARCHAR(60),
    PED_TIPOMOVIMENTACAO  INTEGER NOT NULL,
    PED_TIPODESCRICAO     VARCHAR(30),
    PED_UNIDADE           INTEGER,
    PED_QUANTIDADE        NUMERIC(18,2) DEFAULT 0.0,
    PED_LISTA_PRECO       NUMERIC(18,2),
    PED_DESCONTO          NUMERIC(18,2),
    PED_QTD_DISPONIVEL    NUMERIC(18,2) DEFAULT 0.0,
    PED_VLRUNITARIO       NUMERIC(18,2),
    PED_VLRTOTAL          NUMERIC(18,2),
    PED_REAJUSTE          NUMERIC(18,2),
    PED_DTPEDIDO          DATE,
    PED_DTENTRADA         DATE,
    PED_DTPRAZOENTREGA    DATE,
    PED_ORDEMVENDA        INTEGER NOT NULL
);



/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE EMISSAO_NFE ADD CONSTRAINT PK_EMISSAO_NFE PRIMARY KEY (EMI_NUMERO, EMI_TIPOMOVIMENTACAO, EMI_PESSOA, EMI_EMPRESA);
ALTER TABLE FATURAMENTO ADD CONSTRAINT PK_FATURAMENTO PRIMARY KEY (FAT_CODIGO_PEDIDO, FAT_PESSOA, FAT_EMPRESA);
ALTER TABLE PEDIDOVENDA ADD CONSTRAINT PK_PEDIDOVENDA PRIMARY KEY (PED_NUMERO, PED_PESSOA, PED_EMPRESA, PED_DEPOSITO, PED_PRODUTO, PED_TIPOMOVIMENTACAO);
