
/******************************************************************************/
/***                               Generators                               ***/
/******************************************************************************/

CREATE GENERATOR GEN_BLOCO;
SET GENERATOR GEN_BLOCO TO 4;

CREATE GENERATOR GEN_CATEGORIA;
SET GENERATOR GEN_CATEGORIA TO 5;

CREATE GENERATOR GEN_ESTOQUE;
SET GENERATOR GEN_ESTOQUE TO 0;

CREATE GENERATOR GEN_ESTOQ_MOVIMENTO;
SET GENERATOR GEN_ESTOQ_MOVIMENTO TO 0;

CREATE GENERATOR GEN_MARCAS;
SET GENERATOR GEN_MARCAS TO 2;

CREATE GENERATOR GEN_PESSOAS;
SET GENERATOR GEN_PESSOAS TO 0;

CREATE GENERATOR GEN_PRATELEIRA;
SET GENERATOR GEN_PRATELEIRA TO 5;

CREATE GENERATOR GEN_PRODUTOS;
SET GENERATOR GEN_PRODUTOS TO 1;

CREATE GENERATOR GEN_UNIDADE;
SET GENERATOR GEN_UNIDADE TO 1;


CREATE TABLE BLOCO (
    BLOC_EMPRESA    INTEGER NOT NULL,
    BLOC_CODIGO     INTEGER NOT NULL,
    BLOC_DESCRICAO  VARCHAR(60) NOT NULL,
    BLOC_OBS        VARCHAR(100),
    BLOC_QTDMAXIMA  INTEGER NOT NULL,
    BLOC_CATEGORIA  INTEGER NOT NULL
);

CREATE TABLE CATEGORIA (
    CAT_EMPRESA    INTEGER NOT NULL,
    CAT_CODIGO     INTEGER NOT NULL,
    CAT_DESCRICAO  VARCHAR(60) NOT NULL,
    CAT_NCM        VARCHAR(20),
    CAT_OBS        VARCHAR(100)
);

CREATE TABLE EMPRESA (
    EMP_COD       INTEGER NOT NULL,
    EMP_CNPJ      VARCHAR(14) NOT NULL,
    EMP_RAZAO     VARCHAR(60),
    EMP_NOMEF     VARCHAR(60),
    EMP_ENDERECO  VARCHAR(60),
    EMP_END_NUM   INTEGER,
    EMP_BAIRRO    VARCHAR(20),
    EMP_CIDADE    VARCHAR(60),
    EMP_UF        VARCHAR(2),
    EMP_CEP       VARCHAR(9),
    EMP_FONE      VARCHAR(14),
    EMP_TITULAR   VARCHAR(60)
);

CREATE TABLE ESTOQ_MOVIMENTO (
    EM_EMPRESA             INTEGER NOT NULL,
    EM_PRODUTO             VARCHAR(30) NOT NULL,
    EM_BLOCO               INTEGER NOT NULL,
    EM_PRATELEIRA          INTEGER NOT NULL,
    EM_ESTOQUE             INTEGER NOT NULL,
    EM_CODIGO              INTEGER NOT NULL,
    EM_TIPO                VARCHAR(2) NOT NULL,
    EM_QTD                 NUMERIC(18,2) DEFAULT 0.0 NOT NULL,
    EM_DATA                TIMESTAMP DEFAULT CURRENT_DATE,
    EM_OBS                 VARCHAR(100),
    EM_VALOR_FINANCEIRO    NUMERIC(18,2) DEFAULT 0.0,
    EM_PEDIDOCOMPRAORIGEM  INTEGER,
	EM_DPTO INTEGER NOT NULL
);

CREATE TABLE ESTOQUE (
    ESTOQ_EMPRESA     INTEGER NOT NULL,
    ESTOQ_PRODUTO     VARCHAR(30) NOT NULL,
    ESTOQ_BLOCO       INTEGER NOT NULL,
    ESTOQ_PRATELEIRA  INTEGER NOT NULL,
    ESTOQ_CODIGO      INTEGER NOT NULL,
    ESTOQ_STATUS      VARCHAR(2) DEFAULT 'A',
    ESTOQ_QTD         NUMERIC(18,2) DEFAULT 0.0 NOT NULL,
    ESTOQ_QTDMIN      NUMERIC(18,2) DEFAULT 0.0,
    ESTOQ_QTDMAX      NUMERIC(18,2) DEFAULT 0.0,
    ESTOQ_CUSTOMEDIO  NUMERIC(18,2) DEFAULT 0.0,
    ESTOQ_CATEGORIA   INTEGER,
    ESTOQ_TIPO        INTEGER,
    ESTOQ_DTCADASTRO  DATE DEFAULT CURRENT_DATE,
    ESTOQ_OBS         VARCHAR(100),
    ESTOQ_CHAVE       VARCHAR(10)
);

CREATE TABLE MARCAS (
    MARC_CODIGO     INTEGER NOT NULL,
    MARC_DESCRICAO  VARCHAR(60) NOT NULL,
    MARC_OBS        VARCHAR(100)
);

CREATE TABLE PRATELEIRA (
    PRAT_EMPRESA    INTEGER NOT NULL,
    PRAT_BLOCO      INTEGER NOT NULL,
    PRAT_CODIGO     INTEGER NOT NULL,
    PRAT_DESCRICAO  VARCHAR(60) NOT NULL,
    PRAT_OBS        VARCHAR(100),
    PRAT_QTDMAXIMA  INTEGER NOT NULL,
    PRAT_CATEGORIA  INTEGER NOT NULL
);

CREATE TABLE PRODUTOS (
    PRO_EMPRESA       INTEGER NOT NULL,
    PRO_CODIGO        VARCHAR(30) NOT NULL,
    PRO_CODREF        VARCHAR(30),
    PRO_CODBARRAS     VARCHAR(60),
    PRO_STATUS        VARCHAR(5) DEFAULT 'A',
    PRO_DTCADASTRO    DATE DEFAULT CURRENT_DATE,
    PRO_CLASSFISCAL   VARCHAR(30),
    PRO_CSTCSOSN      VARCHAR(30),
    PRO_NCMSH         VARCHAR(30),
    PRO_EXTIPI        VARCHAR(30),
    PRO_SITTRIB       VARCHAR(30),
    PRO_PIS           VARCHAR(20),
    PRO_COFINS        VARCHAR(18),
    PRO_CSTPIS        VARCHAR(18),
    PRO_ESTATUAL      VARCHAR(20),
    PRO_DESCRICAO     VARCHAR(60) NOT NULL,
    PRO_UNID          INTEGER,
    PRO_MARCA         INTEGER,
    PRO_MOEDA         VARCHAR(10),
    PRO_CATEGORIA     INTEGER NOT NULL,
    PRO_PESO          NUMERIC(18,2) DEFAULT 0.0,
    PRO_CUSTOMEDIO    NUMERIC(18,2) DEFAULT 0.0,
    PRO_VALORIZACAO   NUMERIC(18,2) DEFAULT 0.0,
    PRO_VLRFRETE      NUMERIC(18,2) DEFAULT 0.0,
    PRO_PERCENCARG    NUMERIC(18,2) DEFAULT 0.0,
    PRO_VLRENCARG     NUMERIC(18,2) DEFAULT 0.0,
    PRO_PERCMARGLUCR  NUMERIC(18,2) DEFAULT 0.0,
    PRO_VLRMARGLUCR   NUMERIC(18,2) DEFAULT 0.0,
    PRO_VLRVENDA      NUMERIC(18,2) DEFAULT 0.0,
    PRO_OBS           VARCHAR(100),
    PRO_IMG           BLOB SUB_TYPE 0 SEGMENT SIZE 4096,
    PRO_GRUPO         CHAR(1)
);

CREATE TABLE UNIDADE (
    UN_CODIGO     INTEGER NOT NULL,
    UN_DESCRICAO  VARCHAR(60) NOT NULL,
    UN_OBS        VARCHAR(100)
);



/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE BLOCO ADD CONSTRAINT PK_BLOCO PRIMARY KEY (BLOC_EMPRESA, BLOC_CODIGO);
ALTER TABLE CATEGORIA ADD CONSTRAINT PK_CATEGORIA PRIMARY KEY (CAT_EMPRESA, CAT_CODIGO);
ALTER TABLE EMPRESA ADD CONSTRAINT PK_EMPRESA PRIMARY KEY (EMP_COD);
ALTER TABLE ESTOQUE ADD CONSTRAINT PK_ESTOQUE PRIMARY KEY (ESTOQ_EMPRESA, ESTOQ_PRODUTO, ESTOQ_BLOCO, ESTOQ_PRATELEIRA, ESTOQ_CODIGO);
ALTER TABLE ESTOQ_MOVIMENTO ADD CONSTRAINT PK_ESTOQ_MOVIMENTO PRIMARY KEY (EM_EMPRESA, EM_PRODUTO, EM_BLOCO, EM_PRATELEIRA, EM_ESTOQUE, EM_CODIGO);
ALTER TABLE MARCAS ADD CONSTRAINT PK_MARCAS PRIMARY KEY (MARC_CODIGO);
ALTER TABLE PRATELEIRA ADD CONSTRAINT PK_PRATELEIRA PRIMARY KEY (PRAT_EMPRESA, PRAT_BLOCO, PRAT_CODIGO);
ALTER TABLE PRODUTOS ADD CONSTRAINT PK_PRODUTOS PRIMARY KEY (PRO_EMPRESA, PRO_CODIGO);
ALTER TABLE UNIDADE ADD CONSTRAINT PK_UNIDADE PRIMARY KEY (UN_CODIGO);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE ESTOQUE ADD CONSTRAINT FK_ESTOQUE_BLOCO FOREIGN KEY (ESTOQ_EMPRESA, ESTOQ_BLOCO) REFERENCES BLOCO (BLOC_EMPRESA, BLOC_CODIGO);
ALTER TABLE ESTOQUE ADD CONSTRAINT FK_ESTOQUE_EMPRESA FOREIGN KEY (ESTOQ_EMPRESA) REFERENCES EMPRESA (EMP_COD);
ALTER TABLE ESTOQUE ADD CONSTRAINT FK_ESTOQUE_PRATELEIRA FOREIGN KEY (ESTOQ_EMPRESA, ESTOQ_BLOCO, ESTOQ_PRATELEIRA) REFERENCES PRATELEIRA (PRAT_EMPRESA, PRAT_BLOCO, PRAT_CODIGO);
ALTER TABLE ESTOQUE ADD CONSTRAINT FK_ESTOQUE_PRODUTO FOREIGN KEY (ESTOQ_EMPRESA, ESTOQ_PRODUTO) REFERENCES PRODUTOS (PRO_EMPRESA, PRO_CODIGO);
ALTER TABLE ESTOQ_MOVIMENTO ADD CONSTRAINT FK_EM_ESTOQUE FOREIGN KEY (EM_EMPRESA, EM_PRODUTO, EM_BLOCO, EM_PRATELEIRA, EM_ESTOQUE) REFERENCES ESTOQUE (ESTOQ_EMPRESA, ESTOQ_PRODUTO, ESTOQ_BLOCO, ESTOQ_PRATELEIRA, ESTOQ_CODIGO);
ALTER TABLE ESTOQ_MOVIMENTO ADD CONSTRAINT FK_REL_EM_EMPRESA FOREIGN KEY (EM_EMPRESA) REFERENCES EMPRESA (EMP_COD);
ALTER TABLE PRATELEIRA ADD CONSTRAINT FK_REL_PRAT_BLOCO FOREIGN KEY (PRAT_EMPRESA, PRAT_BLOCO) REFERENCES BLOCO (BLOC_EMPRESA, BLOC_CODIGO);
ALTER TABLE PRATELEIRA ADD CONSTRAINT FK_REL_PRAT_CATEGORIA FOREIGN KEY (PRAT_EMPRESA, PRAT_CATEGORIA) REFERENCES CATEGORIA (CAT_EMPRESA, CAT_CODIGO);
ALTER TABLE PRATELEIRA ADD CONSTRAINT FK_REL_PRAT_EMPRESA FOREIGN KEY (PRAT_EMPRESA) REFERENCES EMPRESA (EMP_COD);
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PROMARC FOREIGN KEY (PRO_MARCA) REFERENCES MARCAS (MARC_CODIGO);
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_REL_PRO_CATEGORIA FOREIGN KEY (PRO_EMPRESA, PRO_CATEGORIA) REFERENCES CATEGORIA (CAT_EMPRESA, CAT_CODIGO);
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_REL_PRO_EMPRESA FOREIGN KEY (PRO_EMPRESA) REFERENCES EMPRESA (EMP_COD);
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_REL_PRO_UNIDADE FOREIGN KEY (PRO_UNID) REFERENCES UNIDADE (UN_CODIGO);


CREATE OR ALTER PROCEDURE ESTOQUE_DELETA_TUDO
AS
begin
    delete from estoq_movimento;
    delete from estoque;
    delete from produtos;
    delete from prateleira;
    delete from bloco;
    delete from categoria;
    delete from marcas;
end^

